using System.ComponentModel;

namespace stockmanagementapi.Enums
{
  public enum ColourEnum
  {
    [Description("Red")]
    Red,
    [Description("Blue")]
    Blue,
    [Description("Green")]
    Green,
    [Description("Black")]
    Black,
    [Description("White")]
    White,
    [Description("Silver")]
    Silver,
    [Description("Gray")]
    Gray,
    [Description("Yellow")]
    Yellow,
    [Description("Orange")]
    Orange,
    [Description("Brown")]
    Brown,
    [Description("Purple")]
    Purple,
    [Description("Pink")]
    Pink,
    [Description("Beige")]
    Beige,
    [Description("Gold")]
    Gold,
    [Description("Maroon")]
    Maroon,
    [Description("Navy")]
    Navy,
    [Description("Teal")]
    Teal,
    [Description("Turquoise")]
    Turquoise,
    [Description("Magenta")]
    Magenta,
    [Description("Lime")]
    Lime,
    [Description("Olive")]
    Olive,
    [Description("Cyan")]
    Cyan,
    [Description("Ivory")]
    Ivory,
    [Description("Bronze")]
    Bronze,
    [Description("Charcoal")]
    Charcoal,
    [Description("Champagne")]
    Champagne,
    [Description("Burgundy")]
    Burgundy,
    [Description("Mint")]
    Mint,
    [Description("Peach")]
    Peach
  }
}
