// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stockmanagementapi.Models;

#nullable disable

namespace stockmanagementapi.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    [Migration("20250128115341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("stockmanagementapi.Models.StockAccessories.StockAccessory", b =>
                {
                    b.Property<int>("StockAccessoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockAccessoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StockAccessoryId");

                    b.ToTable("StockAccessories");
                });

            modelBuilder.Entity("stockmanagementapi.Models.StockItems.StockItem", b =>
                {
                    b.Property<int>("StockItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockItemId"));

                    b.Property<int>("Colour")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KMS")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StockItemId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("stockmanagementapi.Models.StockItemsAccessories.StockItemAccessory", b =>
                {
                    b.Property<int>("StockItemId")
                        .HasColumnType("int");

                    b.Property<int>("StockAccessoryId")
                        .HasColumnType("int");

                    b.Property<int>("StockItemAccessoryId")
                        .HasColumnType("int");

                    b.HasKey("StockItemId", "StockAccessoryId");

                    b.HasIndex("StockAccessoryId");

                    b.ToTable("StockItemAccessories");
                });

            modelBuilder.Entity("stockmanagementapi.Models.StockItemsAccessories.StockItemAccessory", b =>
                {
                    b.HasOne("stockmanagementapi.Models.StockAccessories.StockAccessory", "StockAccessory")
                        .WithMany("StockItemAccessories")
                        .HasForeignKey("StockAccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("stockmanagementapi.Models.StockItems.StockItem", "StockItem")
                        .WithMany("StockItemAccessories")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockAccessory");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("stockmanagementapi.Models.StockAccessories.StockAccessory", b =>
                {
                    b.Navigation("StockItemAccessories");
                });

            modelBuilder.Entity("stockmanagementapi.Models.StockItems.StockItem", b =>
                {
                    b.Navigation("StockItemAccessories");
                });
#pragma warning restore 612, 618
        }
    }
}
